version: '3'
services:
    app:
        build: .
        ports:
            - "8085:8085"
        volumes:
            - .:/app
        environment:
            FLASK_ENV: development
        depends_on:
            - postgres
            - redis
    redis:
        image: redis:alpine
    postgres:
        env_file: 
            - .env
        image: postgres:latest
        networks:
            - default
        ports:
            - 5405:5432
        restart: always
        volumes:
            - ./postgres-data:/var/lib/postgresql/data