version: '3'
services:
    app:
        build: .
        ports:
            - "8085:8085"
        volumes:
            - .:/app
        environment:
            FLASK_ENV: development
        depends_on:
            - redis
    redis:
        image: redis:alpine